ADD: 헤더 태그 검색 기능
EntryDSM/Haagen-Dazs pull request #12
Opened 2019-09-07 14:03 UTC by soheejang15

# ADD: 헤더 태그 검색 기능
## 목적
### 요약
태그 검색 기능을 구현했습니다.

2019-09-07 14:23 UTC, junu126 requested changes

2019-09-07 14:23 UTC, junu126 commented on haagen-dazs/src/components/HeaderSearchBar/index.tsx
> +  if (e.target.value !== "") {
`if (e.target.value) {}` 이거로 바꿀 수 있을 거 같아요!

2019-09-08 13:19 UTC, soheejang15 commented on haagen-dazs/src/components/HeaderSearchBar/index.tsx
> +  if (e.target.value !== "") {
수정했습니다.

2019-09-08 13:26 UTC, junu126 requested changes

2019-09-08 13:26 UTC, junu126 commented on haagen-dazs/src/components/HeaderSearchBar/index.tsx
> +import { Keyword } from "./style";
Who are you?

2019-09-08 13:26 UTC, junu126 commented on haagen-dazs/src/components/HeaderSearchBar/index.tsx
>    useEffect(() => {
useEffect를 여러번 쓰면 좋을거 가타요

2019-09-08 13:33 UTC, soheejang15 commented on haagen-dazs/src/components/HeaderSearchBar/index.tsx
> +import { Keyword } from "./style";
^^

2019-09-08 13:33 UTC, soheejang15 commented on haagen-dazs/src/components/HeaderSearchBar/index.tsx
>    useEffect(() => {
수정했서요

2019-09-09 02:06 UTC, junu126 approved these changes

2019-09-12 08:06 UTC, zzelcyy approved these changes

2019-09-20 01:56 UTC, engolder commented on haagen-dazs/src/components/HeaderSearchBar/index.tsx
> +  if (e.target.value !== "") {
난 이거 이전게 더 낫다고생각함. 거짓임직한 값보다는 거짓이 확실하니까.

2019-09-20 02:04 UTC, engolder requested changes
와 잠만 이거 문제가 좀 많은코드인듯 집가서봄

2019-09-20 02:04 UTC, engolder commented on haagen-dazs/src/components/HeaderSearchBar/index.tsx
> +  const [keywordsList, setKeywordsList] = useState([]);
useState<string[]>([])

2019-09-20 10:24 UTC, engolder requested changes

2019-09-20 10:24 UTC, engolder commented on haagen-dazs/src/components/HeaderSearchBar/index.tsx
> +          placeholder={!keywordsList.length ? "검색어를 입력해주세요." : ""}
list.length > 0 ? “” : “.....”

2019-09-20 10:24 UTC, engolder commented on haagen-dazs/package.json
> +    "webpack-dev-server": "^3.8.0"
이친구들은 dev deps에 있어야할거같은데??

2019-09-20 14:15 UTC, soheejang15 commented on haagen-dazs/src/components/HeaderSearchBar/index.tsx
> +  const [keywordsList, setKeywordsList] = useState([]);
수정했습니다 감사합니다😊

2019-09-20 14:18 UTC, soheejang15 commented on haagen-dazs/src/components/HeaderSearchBar/index.tsx
> +          placeholder={!keywordsList.length ? "검색어를 입력해주세요." : ""}
수정했습니다 감사합니다😊

2019-09-20 14:21 UTC, soheejang15 commented on haagen-dazs/src/components/HeaderSearchBar/index.tsx
> +  if (e.target.value !== "") {
"회사가서 얻은 게 많은가 보네요 좋은 정보 감사" - 준우
@engolder

2019-09-23 02:17 UTC, engolder requested changes

2019-09-23 02:17 UTC, engolder commented on haagen-dazs/src/utils/Header/style.ts
>    border: solid 0.5px #65bbb7;
0.5px

2019-09-23 02:17 UTC, engolder commented on haagen-dazs/src/utils/Header/style.ts
> +    > span {
span태그는 이부분 성격에 잘 안맞는듯. 원래 문법이면 span태그 child로 block 요소를 적을수없음(물론 지금은 display를 inline-flex로 해서 가능하긴한데,). 다른태그를 찾아보쟈

2019-09-23 02:17 UTC, engolder commented on haagen-dazs/src/components/HeaderSearchBar/style.ts
> +  opacity: 0.6;
투명도가 왜있지 아니 뭐 그럴순있지

2019-09-23 02:17 UTC, engolder commented on haagen-dazs/src/components/SearchCreteriaSelectBox/index.tsx
> +class SearchCreteriaSelectBox extends React.Component<Props, null> {
근데 왜 요건 class component야? 다 functional로 쓰는게 낫지않을까

2019-09-23 07:00 UTC, soheejang15 commented on haagen-dazs/src/utils/Header/style.ts
>    border: solid 0.5px #65bbb7;
수정했습니다

2019-09-23 07:04 UTC, soheejang15 commented on haagen-dazs/src/components/HeaderSearchBar/style.ts
> +  opacity: 0.6;
텍스트에 투명도 설정되어있어서 이렇게 썼는데, rgba로 변경해서 적용할까요?

2019-09-23 07:05 UTC, engolder commented on haagen-dazs/src/components/HeaderSearchBar/style.ts
> +  opacity: 0.6;
노노 갠찮음

2019-09-23 07:06 UTC, soheejang15 commented on haagen-dazs/src/components/SearchCreteriaSelectBox/index.tsx
> +class SearchCreteriaSelectBox extends React.Component<Props, null> {
state를 쓸 것 같아서 class component로 작성했었는데, 하다보니 state가 필요 없더라구요 😊 수정했습니다

2019-09-23 07:18 UTC, soheejang15 commented on haagen-dazs/src/utils/Header/style.ts
> +    > span {
수정했습니다.

2019-09-23 14:14 UTC, merged