CREATE: Admin page pagination
EntryDSM/Haagen-Dazs pull request #13
Opened 2019-10-01 14:51 UTC by soheejang15

# CREATE: Admin page pagination
## 어드민 페이지 지원자 리스트 페이지네이션 구현하였습니다.

2019-10-02 01:54 UTC, junu126 requested changes
ㅎㅇㅌ

2019-10-02 01:54 UTC, junu126 commented on haagen-dazs/src/components/ApplicantList/index.tsx
> +};
```ts
const checkType = (type: string): string => {
  switch (type) {
    case "common":
      return  "일반전형";
    case "social":
      return "사회통합전형";
    case "meister":
      return "마이스터전형";
    default:
      returnWord = "";
  }
};
```

2019-10-02 01:54 UTC, junu126 commented on haagen-dazs/src/components/ApplicantList/index.tsx
> +    }}
이렇게 하지말고
함수로 빼주세요.

린트가 싫어해요

2019-10-02 01:54 UTC, junu126 commented on haagen-dazs/src/components/ApplicantListContainer/index.tsx
> +    <table style={{ width: "100%" }}>
?????????????????????

2019-10-02 02:10 UTC, engolder commented on haagen-dazs/src/components/ApplicantList/index.tsx
> +    }}
린트꺼버리셈

2019-10-02 02:10 UTC, engolder commented on haagen-dazs/src/components/ApplicantList/index.tsx
> +    }}
`checkApplicantSubmissionStatus(applicantData.submit === 1);`

2019-10-05 04:48 UTC, engolder requested changes

2019-10-05 04:48 UTC, engolder commented on haagen-dazs/src/components/ApplicantList/index.tsx
> +};
```ts
enum AdmissionType {
  common = "일반전형",
  social = "사회통합전형",
  meister = "마이스터전형",
}
```
그리고 이거 컴포넌트 선언 구문 밖으로 빼주세요

2019-10-05 04:48 UTC, engolder commented on haagen-dazs/src/components/ApplicantList/index.tsx
> +    <S.TD>{applicantData.region === "daejeon" ? "대전" : "전국"}</S.TD>
이거도 region enum 만들어서
Region[applicantData.region]으로 쓸 수 있도록

2019-10-05 04:48 UTC, engolder commented on haagen-dazs/src/components/ApplicantList/index.tsx
> +    </S.TD>
```tsx
  [applicantData.arrive, applicantData.paid, applicantData.submit].map(data => (
    <S.TD>
      <S.CheckBoxIcon>
        {data === 1 && <img src={checked} alt="checked" />}
      </S.CheckBoxIcon>
    </S.TD>
  )
```

2019-10-05 04:48 UTC, engolder commented on haagen-dazs/src/pages/AdminPage/index.tsx
> +  region: string;
이거 근데 server api 에서 field name "isDajeon"같은거 아니었나? 맞으면 그거랑 맞추는게 좋을듯

2019-10-05 04:48 UTC, engolder commented on haagen-dazs/src/pages/AdminPage/index.tsx
> +  type: string;
union으로 변경

2019-10-05 04:48 UTC, engolder commented on haagen-dazs/src/pages/AdminPage/index.tsx
> +  arrive: number;
number?? 이거 설명좀 뭔지모름

2019-10-05 04:48 UTC, engolder commented on haagen-dazs/src/pages/AdminPage/index.tsx
> +  currentList: ListItem[];
`currentListItems: ListItem[];`
특정 object의 list type은 복수형으로 쓰는것이 좋음. 나중에 햇갈림

2019-10-05 04:48 UTC, engolder commented on haagen-dazs/src/pages/AdminPage/index.tsx
> +  list: ListItem[];
listItems

2019-10-05 04:48 UTC, engolder commented on haagen-dazs/src/pages/AdminPage/index.tsx
>    public state: State = {
이거 타이핑해줘야 했던가 안해도될거같은데 확인좀

2019-10-05 04:48 UTC, engolder commented on haagen-dazs/src/pages/AdminPage/index.tsx
> +    this.setState({ numberOfPages: Math.ceil(this.state.list.length / 10) });
length가 0이라면..? 그리고 length는 애초에 decimal이라서 ceiling안해줘도됨

2019-10-05 04:48 UTC, engolder commented on haagen-dazs/src/pages/AdminPage/index.tsx
> +    this.setState({ currentList });
state updating은 가능하면 동시에 해주는게 좋을듯, 가독성에도 좋고 나중에 코드문제 생길때 디버깅에용이

2019-10-05 04:48 UTC, engolder commented on haagen-dazs/src/pages/AdminPage/index.tsx
> +    const currentList: ListItem[] = this.state.list.slice(0, 10);
혹시 lint에서 걸리나? `this.state.list.slice(10)`

2019-10-05 04:48 UTC, engolder commented on haagen-dazs/src/pages/AdminPage/index.tsx
> +      );
? 잠시만

2019-10-05 04:48 UTC, engolder commented on haagen-dazs/src/pages/AdminPage/index.tsx
> +      );
pagination을 왜 client에서함? 서버에서 api paging으로 바꾸라고해ㅐ

2019-10-05 04:51 UTC, junu126 commented on haagen-dazs/src/pages/AdminPage/index.tsx
> +    const currentList: ListItem[] = this.state.list.slice(0, 10);
안걸림

2019-10-05 04:52 UTC, junu126 commented on haagen-dazs/src/pages/AdminPage/index.tsx
> +      );
오늘안에 완성해야해서
플로우 수정은 불가능 할듯

하지만 나도 동의

2019-10-05 14:17 UTC, soheejang15 commented on haagen-dazs/src/components/ApplicantList/index.tsx
> +};
수정했습니다 ☺️

2019-10-05 14:18 UTC, soheejang15 commented on haagen-dazs/src/components/ApplicantList/index.tsx
> +    }}
수정했습니다 ☺️

2019-10-05 14:18 UTC, soheejang15 commented on haagen-dazs/src/components/ApplicantListContainer/index.tsx
> +    <table style={{ width: "100%" }}>
ㅎㅎㅎㅎㅎㅎㅎ수정했습니다

2019-10-05 14:40 UTC, soheejang15 commented on haagen-dazs/src/components/ApplicantList/index.tsx
> +    <S.TD>{applicantData.region === "daejeon" ? "대전" : "전국"}</S.TD>
수정했습니다 ☺️

2019-10-05 14:44 UTC, soheejang15 commented on haagen-dazs/src/components/ApplicantList/index.tsx
> +    </S.TD>
수정했습니다 ☺️

2019-10-05 14:44 UTC, soheejang15 commented on haagen-dazs/src/pages/AdminPage/index.tsx
> +  region: string;
수정했습니다 ☺️

2019-10-05 14:56 UTC, soheejang15 commented on haagen-dazs/src/pages/AdminPage/index.tsx
> +  arrive: number;
다른 api랑 혼동했습니다 ㅎㅎㅎ.. 수정했어요!

2019-10-05 14:59 UTC, soheejang15 commented on haagen-dazs/src/pages/AdminPage/index.tsx
> +  currentList: ListItem[];
수정했습니다 ☺️

2019-10-05 15:00 UTC, soheejang15 commented on haagen-dazs/src/pages/AdminPage/index.tsx
> +  list: ListItem[];
수정했습니다 ☺️

2019-10-08 16:44 UTC, merged